import { Property } from '../models/property.model';

export const MOCK_PROPERTIES: Property[] = [
  {
    id: 1,
    nome: 'Apartamento Vista Mar no Cabo Branco',
    descricao_curta: 'Apartamento ventilado com varanda gourmet e vista lateral para o mar.',
    descricao:
      'Planta inteligente, sala integrada, cozinha planejada e localizacao privilegiada a poucos metros da orla de Cabo Branco.',
    preco: 820000,
    cidade: 'Joao Pessoa',
    bairro: 'Cabo Branco',
    endereco: 'Av. Cabo Branco, 1820',
    tipo: 'Apartamento',
    area: 94,
    quartos: 3,
    banheiros: 3,
    garagem: 2,
    status: 'Disponivel',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    imagens: [],
  },
  {
    id: 2,
    nome: 'Casa Familiar no Altiplano',
    descricao_curta: 'Casa ampla com jardim, suite master e area social integrada.',
    descricao:
      'Imovel ideal para familias que buscam conforto, seguranca e espacos generosos em um dos bairros mais valorizados de Joao Pessoa.',
    preco: 1380000,
    cidade: 'Joao Pessoa',
    bairro: 'Altiplano',
    endereco: 'Rua Bancario Sergio Guerra, 455',
    tipo: 'Casa',
    area: 238,
    quartos: 4,
    banheiros: 5,
    garagem: 4,
    status: 'Disponivel',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    imagens: [],
  },
  {
    id: 3,
    nome: 'Studio Executivo em Tambau',
    descricao_curta: 'Studio mobiliado, compacto e pronto para morar ou investir.',
    descricao:
      'Localizacao estrategica perto da praia, de restaurantes, servicos essenciais e areas de lazer da cidade.',
    preco: 390000,
    cidade: 'Joao Pessoa',
    bairro: 'Tambau',
    endereco: 'Av. Almirante Tamandare, 612',
    tipo: 'Studio',
    area: 39,
    quartos: 1,
    banheiros: 1,
    garagem: 1,
    status: 'Disponivel',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    imagens: [],
  },
];
